package org.oasis.springbootdemo.dao;

import org.apache.ibatis.annotations.Param;
import org.oasis.springbootdemo.model.generated.CsContactStat;
import org.oasis.springbootdemo.model.generated.CsContactStatExample;

import java.util.List;
import java.util.Set;

public interface CsContactStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    long countByExample(CsContactStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    int deleteByExample(CsContactStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    int insert(CsContactStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    int insertSelective(CsContactStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    List<CsContactStat> selectByExample(CsContactStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    CsContactStat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CsContactStat record, @Param("example") CsContactStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CsContactStat record, @Param("example") CsContactStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CsContactStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_contact_stat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CsContactStat record);

    Set<Long> selectPrimaryKeys(@Param("idList") List<Long> idList, @Param("queryTime") Long queryTime);
}