package org.oasis.springbootdemo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.oasis.springbootdemo.model.generated.TextbookItem;
import org.oasis.springbootdemo.model.generated.TextbookItemExample;

public interface TextbookItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    long countByExample(TextbookItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    int deleteByExample(TextbookItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    int insert(TextbookItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    int insertSelective(TextbookItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    List<TextbookItem> selectByExample(TextbookItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    TextbookItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TextbookItem record, @Param("example") TextbookItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TextbookItem record, @Param("example") TextbookItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TextbookItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TextbookItem record);
}